name: Snyk monitor scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
      - name: Snyk Authentication
        run: snyk auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
